//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNConnect.CKE.Controls
{
    public partial class JoditEditorOptions
    {
        /// <summary>
        /// lblEditorMode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEditorMode;

        /// <summary>
        /// ddlEditorMode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEditorMode;

        /// <summary>
        /// lblDefaultHeight control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDefaultHeight;

        /// <summary>
        /// txtDefaultHeight control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDefaultHeight;

        /// <summary>
        /// lblHeightUnit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblHeightUnit;

        /// <summary>
        /// lblToolbarSticky control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblToolbarSticky;

        /// <summary>
        /// chkToolbarSticky control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkToolbarSticky;

        /// <summary>
        /// lblShowCharsCounter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblShowCharsCounter;

        /// <summary>
        /// chkShowCharsCounter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkShowCharsCounter;

        /// <summary>
        /// lblShowWordsCounter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblShowWordsCounter;

        /// <summary>
        /// chkShowWordsCounter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkShowWordsCounter;

        /// <summary>
        /// lblShowXPathInStatusbar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblShowXPathInStatusbar;

        /// <summary>
        /// chkShowXPathInStatusbar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkShowXPathInStatusbar;

        /// <summary>
        /// lblAllowResizeY control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAllowResizeY;

        /// <summary>
        /// chkAllowResizeY control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkAllowResizeY;

        /// <summary>
        /// lblSpellcheck control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSpellcheck;

        /// <summary>
        /// chkSpellcheck control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkSpellcheck;

        /// <summary>
        /// lblTheme control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTheme;

        /// <summary>
        /// ddlTheme control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTheme;

        /// <summary>
        /// lblImageUploadEnabled control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblImageUploadEnabled;

        /// <summary>
        /// chkImageUploadEnabled control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkImageUploadEnabled;

        /// <summary>
        /// lblMaxImageFileSize control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMaxImageFileSize;

        /// <summary>
        /// txtMaxImageFileSize control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMaxImageFileSize;

        /// <summary>
        /// lblFileSizeUnit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFileSizeUnit;

        /// <summary>
        /// lblCustomConfig control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCustomConfig;

        /// <summary>
        /// txtCustomConfig control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCustomConfig;

        /// <summary>
        /// lblCustomConfigHelp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCustomConfigHelp;
    }
}